// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from api.djinni

#pragma once

#include "djinni_support.hpp"
#include "hello_model.hpp"

namespace djinni_generated {

class NativeHelloModel final {
public:
    using CppType = ::djinni_rest_gen::HelloModel;
    using JniType = jobject;

    using Boxed = NativeHelloModel;

    ~NativeHelloModel();

    static CppType toCpp(JNIEnv* jniEnv, JniType j);
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c);

private:
    NativeHelloModel();
    friend ::djinni::JniClass<NativeHelloModel>;

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("com/mycompany/djinni_rest/HelloModel") };
    const jmethodID jconstructor { ::djinni::jniGetMethodID(clazz.get(), "<init>", "(Ljava/lang/String;)V") };
    const jfieldID field_mWelcomeTitle { ::djinni::jniGetFieldID(clazz.get(), "mWelcomeTitle", "Ljava/lang/String;") };
};

}  // namespace djinni_generated
