// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from api.djinni

#include "NativeHelloModel.hpp"  // my header
#include "Marshal.hpp"

namespace djinni_generated {

NativeHelloModel::NativeHelloModel() = default;

NativeHelloModel::~NativeHelloModel() = default;

auto NativeHelloModel::fromCpp(JNIEnv* jniEnv, const CppType& c) -> ::djinni::LocalRef<JniType> {
    const auto& data = ::djinni::JniClass<NativeHelloModel>::get();
    auto r = ::djinni::LocalRef<JniType>{jniEnv->NewObject(data.clazz.get(), data.jconstructor,
                                                           ::djinni::get(::djinni::String::fromCpp(jniEnv, c.welcome_title)))};
    ::djinni::jniExceptionCheck(jniEnv);
    return r;
}

auto NativeHelloModel::toCpp(JNIEnv* jniEnv, JniType j) -> CppType {
    ::djinni::JniLocalScope jscope(jniEnv, 2);
    assert(j != nullptr);
    const auto& data = ::djinni::JniClass<NativeHelloModel>::get();
    return {::djinni::String::toCpp(jniEnv, (jstring)jniEnv->GetObjectField(j, data.field_mWelcomeTitle))};
}

}  // namespace djinni_generated
