// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from api.djinni

#include "NativeApiPhotosResponse.hpp"  // my header
#include "Marshal.hpp"
#include "NativePhotoModel.hpp"

namespace djinni_generated {

NativeApiPhotosResponse::NativeApiPhotosResponse() : ::djinni::JniInterface<::djinni_rest_gen::ApiPhotosResponse, NativeApiPhotosResponse>() {}

NativeApiPhotosResponse::~NativeApiPhotosResponse() = default;

NativeApiPhotosResponse::JavaProxy::JavaProxy(JniType j) : Handle(::djinni::jniGetThreadEnv(), j) { }

NativeApiPhotosResponse::JavaProxy::~JavaProxy() = default;

void NativeApiPhotosResponse::JavaProxy::on_index_success(const std::vector<::djinni_rest_gen::PhotoModel> & c_result) {
    auto jniEnv = ::djinni::jniGetThreadEnv();
    ::djinni::JniLocalScope jscope(jniEnv, 10);
    const auto& data = ::djinni::JniClass<::djinni_generated::NativeApiPhotosResponse>::get();
    jniEnv->CallVoidMethod(Handle::get().get(), data.method_onIndexSuccess,
                           ::djinni::get(::djinni::List<::djinni_generated::NativePhotoModel>::fromCpp(jniEnv, c_result)));
    ::djinni::jniExceptionCheck(jniEnv);
}
void NativeApiPhotosResponse::JavaProxy::on_show_success(const ::djinni_rest_gen::PhotoModel & c_result) {
    auto jniEnv = ::djinni::jniGetThreadEnv();
    ::djinni::JniLocalScope jscope(jniEnv, 10);
    const auto& data = ::djinni::JniClass<::djinni_generated::NativeApiPhotosResponse>::get();
    jniEnv->CallVoidMethod(Handle::get().get(), data.method_onShowSuccess,
                           ::djinni::get(::djinni_generated::NativePhotoModel::fromCpp(jniEnv, c_result)));
    ::djinni::jniExceptionCheck(jniEnv);
}
void NativeApiPhotosResponse::JavaProxy::on_failure() {
    auto jniEnv = ::djinni::jniGetThreadEnv();
    ::djinni::JniLocalScope jscope(jniEnv, 10);
    const auto& data = ::djinni::JniClass<::djinni_generated::NativeApiPhotosResponse>::get();
    jniEnv->CallVoidMethod(Handle::get().get(), data.method_onFailure);
    ::djinni::jniExceptionCheck(jniEnv);
}

}  // namespace djinni_generated
