// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from djinni_rest.djinni

#pragma once

#include "djinni_support.hpp"
#include "posts_service.hpp"

namespace djinni_generated {

class NativePostsService final : ::djinni::JniInterface<::djinni_rest::PostsService, NativePostsService> {
public:
    using CppType = std::shared_ptr<::djinni_rest::PostsService>;
    using CppOptType = std::shared_ptr<::djinni_rest::PostsService>;
    using JniType = jobject;

    using Boxed = NativePostsService;

    ~NativePostsService();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativePostsService>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativePostsService>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativePostsService();
    friend ::djinni::JniClass<NativePostsService>;
    friend ::djinni::JniInterface<::djinni_rest::PostsService, NativePostsService>;

};

}  // namespace djinni_generated
