// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from djinni_rest.djinni

#include "NativePostsIndexResponse.hpp"  // my header
#include "Marshal.hpp"
#include "NativePostModel.hpp"

namespace djinni_generated {

NativePostsIndexResponse::NativePostsIndexResponse() : ::djinni::JniInterface<::djinni_rest_gen::PostsIndexResponse, NativePostsIndexResponse>() {}

NativePostsIndexResponse::~NativePostsIndexResponse() = default;

NativePostsIndexResponse::JavaProxy::JavaProxy(JniType j) : Handle(::djinni::jniGetThreadEnv(), j) { }

NativePostsIndexResponse::JavaProxy::~JavaProxy() = default;

void NativePostsIndexResponse::JavaProxy::on_success(const std::vector<::djinni_rest_gen::PostModel> & c_result) {
    auto jniEnv = ::djinni::jniGetThreadEnv();
    ::djinni::JniLocalScope jscope(jniEnv, 10);
    const auto& data = ::djinni::JniClass<::djinni_generated::NativePostsIndexResponse>::get();
    jniEnv->CallVoidMethod(Handle::get().get(), data.method_onSuccess,
                           ::djinni::get(::djinni::List<::djinni_generated::NativePostModel>::fromCpp(jniEnv, c_result)));
    ::djinni::jniExceptionCheck(jniEnv);
}
void NativePostsIndexResponse::JavaProxy::on_failure() {
    auto jniEnv = ::djinni::jniGetThreadEnv();
    ::djinni::JniLocalScope jscope(jniEnv, 10);
    const auto& data = ::djinni::JniClass<::djinni_generated::NativePostsIndexResponse>::get();
    jniEnv->CallVoidMethod(Handle::get().get(), data.method_onFailure);
    ::djinni::jniExceptionCheck(jniEnv);
}

}  // namespace djinni_generated
