// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from djinni_rest.djinni

#pragma once

#include "djinni_support.hpp"
#include "posts_index_response.hpp"

namespace djinni_generated {

class NativePostsIndexResponse final : ::djinni::JniInterface<::djinni_rest_gen::PostsIndexResponse, NativePostsIndexResponse> {
public:
    using CppType = std::shared_ptr<::djinni_rest_gen::PostsIndexResponse>;
    using CppOptType = std::shared_ptr<::djinni_rest_gen::PostsIndexResponse>;
    using JniType = jobject;

    using Boxed = NativePostsIndexResponse;

    ~NativePostsIndexResponse();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativePostsIndexResponse>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativePostsIndexResponse>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativePostsIndexResponse();
    friend ::djinni::JniClass<NativePostsIndexResponse>;
    friend ::djinni::JniInterface<::djinni_rest_gen::PostsIndexResponse, NativePostsIndexResponse>;

    class JavaProxy final : ::djinni::JavaProxyHandle<JavaProxy>, public ::djinni_rest_gen::PostsIndexResponse
    {
    public:
        JavaProxy(JniType j);
        ~JavaProxy();

        void on_success(const std::vector<::djinni_rest_gen::PostModel> & result) override;
        void on_failure() override;

    private:
        friend ::djinni::JniInterface<::djinni_rest_gen::PostsIndexResponse, ::djinni_generated::NativePostsIndexResponse>;
    };

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("com/mycompany/djinni_rest/PostsIndexResponse") };
    const jmethodID method_onSuccess { ::djinni::jniGetMethodID(clazz.get(), "onSuccess", "(Ljava/util/ArrayList;)V") };
    const jmethodID method_onFailure { ::djinni::jniGetMethodID(clazz.get(), "onFailure", "()V") };
};

}  // namespace djinni_generated
