// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from djinni_rest.djinni

#include "NativePostsService.hpp"  // my header
#include "Marshal.hpp"
#include "NativePostModel.hpp"
#include "NativePostsService.hpp"

namespace djinni_generated {

NativePostsService::NativePostsService() : ::djinni::JniInterface<::djinni_rest::PostsService, NativePostsService>("com/mycompany/djinni_rest/PostsService$CppProxy") {}

NativePostsService::~NativePostsService() = default;


CJNIEXPORT void JNICALL Java_com_mycompany_djinni_1rest_PostsService_00024CppProxy_nativeDestroy(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        delete reinterpret_cast<djinni::CppProxyHandle<::djinni_rest::PostsService>*>(nativeRef);
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT jobject JNICALL Java_com_mycompany_djinni_1rest_PostsService_create(JNIEnv* jniEnv, jobject /*this*/)
{
    try {
        DJINNI_FUNCTION_PROLOGUE0(jniEnv);
        auto r = ::djinni_rest::PostsService::create();
        return ::djinni::release(::djinni_generated::NativePostsService::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT jobject JNICALL Java_com_mycompany_djinni_1rest_PostsService_00024CppProxy_native_1getPostsIndex(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::djinni_rest::PostsService>(nativeRef);
        auto r = ref->get_posts_index();
        return ::djinni::release(::djinni::List<::djinni_generated::NativePostModel>::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

}  // namespace djinni_generated
