// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from djinni_rest.djinni

#import "DRPostsService+Private.h"
#import "DRPostsService.h"
#import "DJICppWrapperCache+Private.h"
#import "DJIError.h"
#import "DJIMarshal+Private.h"
#import "DRPostModel+Private.h"
#import "DRPostsService+Private.h"
#include <exception>
#include <utility>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@interface DRPostsService ()

- (id)initWithCpp:(const std::shared_ptr<::djinni_rest::PostsService>&)cppRef;

@end

@implementation DRPostsService {
    ::djinni::CppProxyCache::Handle<std::shared_ptr<::djinni_rest::PostsService>> _cppRefHandle;
}

- (id)initWithCpp:(const std::shared_ptr<::djinni_rest::PostsService>&)cppRef
{
    if (self = [super init]) {
        _cppRefHandle.assign(cppRef);
    }
    return self;
}

+ (nullable DRPostsService *)create {
    try {
        auto r = ::djinni_rest::PostsService::create();
        return ::djinni_generated::PostsService::fromCpp(r);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (nonnull NSArray<DRPostModel *> *)getPostsIndex {
    try {
        auto r = _cppRefHandle.get()->get_posts_index();
        return ::djinni::List<::djinni_generated::PostModel>::fromCpp(r);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

namespace djinni_generated {

auto PostsService::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return objc->_cppRefHandle.get();
}

auto PostsService::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return ::djinni::get_cpp_proxy<DRPostsService>(cpp);
}

}  // namespace djinni_generated

@end
