// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from djinni_rest.djinni

#import "DRPostModel+Private.h"
#import "DJIMarshal+Private.h"
#include <cassert>

namespace djinni_generated {

auto PostModel::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::I64::toCpp(obj.id),
            ::djinni::String::toCpp(obj.title),
            ::djinni::String::toCpp(obj.body)};
}

auto PostModel::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[DRPostModel alloc] initWithId:(::djinni::I64::fromCpp(cpp.id))
                                     title:(::djinni::String::fromCpp(cpp.title))
                                      body:(::djinni::String::fromCpp(cpp.body))];
}

}  // namespace djinni_generated
