// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from djinni_rest.djinni

#include "posts_service.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class DRPostsService;

namespace djinni_generated {

class PostsService
{
public:
    using CppType = std::shared_ptr<::djinni_rest::PostsService>;
    using CppOptType = std::shared_ptr<::djinni_rest::PostsService>;
    using ObjcType = DRPostsService*;

    using Boxed = PostsService;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

