// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from djinni_rest.djinni

#import "DRPostModel.h"
#import <Foundation/Foundation.h>
@class DRPostsService;


@interface DRPostsService : NSObject

+ (nullable DRPostsService *)create;

- (nonnull NSArray<DRPostModel *> *)getPostsIndex;

@end
