// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from djinni_rest.djinni

#import "DRPostModel.h"
#include "post_model.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class DRPostModel;

namespace djinni_generated {

struct PostModel
{
    using CppType = ::djinni_rest::PostModel;
    using ObjcType = DRPostModel*;

    using Boxed = PostModel;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
