// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from api.djinni

#import "NativeHelloModel.h"


@implementation NativeHelloModel

- (nonnull instancetype)initWithWelcomeTitle:(nonnull NSString *)welcomeTitle
{
    if (self = [super init]) {
        _welcomeTitle = [welcomeTitle copy];
    }
    return self;
}

+ (nonnull instancetype)helloModelWithWelcomeTitle:(nonnull NSString *)welcomeTitle
{
    return [[self alloc] initWithWelcomeTitle:welcomeTitle];
}

- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p welcomeTitle:%@>", self.class, self, self.welcomeTitle];
}

@end
