// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from api.djinni

#import "NativePhotoModel.h"
#include "photo_model.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class NativePhotoModel;

namespace djinni_generated {

struct PhotoModel
{
    using CppType = ::djinni_rest_gen::PhotoModel;
    using ObjcType = NativePhotoModel*;

    using Boxed = PhotoModel;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
