// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from api.djinni

#import "NativeHelloModel+Private.h"
#import "DJIMarshal+Private.h"
#include <cassert>

namespace djinni_generated {

auto HelloModel::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::String::toCpp(obj.welcomeTitle)};
}

auto HelloModel::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[NativeHelloModel alloc] initWithWelcomeTitle:(::djinni::String::fromCpp(cpp.welcome_title))];
}

}  // namespace djinni_generated
