// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from djinni_rest.djinni

#import "NativeApiResponse+Private.h"
#import "NativeApiResponse.h"
#import "DJIMarshal+Private.h"
#import "DJIObjcWrapperCache+Private.h"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

namespace djinni_generated {

class ApiResponse::ObjcProxy final
: public ::djinni_rest_gen::ApiResponse
, public ::djinni::ObjcProxyCache::Handle<ObjcType>
{
public:
    using Handle::Handle;
    void on_success(const std::string & c_result) override
    {
        @autoreleasepool {
            [Handle::get() onSuccess:(::djinni::String::fromCpp(c_result))];
        }
    }
    void on_failure() override
    {
        @autoreleasepool {
            [Handle::get() onFailure];
        }
    }
};

}  // namespace djinni_generated

namespace djinni_generated {

auto ApiResponse::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return ::djinni::get_objc_proxy<ObjcProxy>(objc);
}

auto ApiResponse::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return dynamic_cast<ObjcProxy&>(*cpp).Handle::get();
}

}  // namespace djinni_generated
