// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from api.djinni

#import "NativePhotoModel.h"
#import <Foundation/Foundation.h>


@protocol NativeApiPhotosResponse

- (void)onIndexSuccess:(nonnull NSArray<NativePhotoModel *> *)result;

- (void)onShowSuccess:(nonnull NativePhotoModel *)result;

- (void)onFailure;

@end
