// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from djinni_rest.djinni

#import <Foundation/Foundation.h>
@class NativeApi;
@protocol NativeThreadLauncher;


@interface NativeApi : NSObject

+ (nullable NativeApi *)createApi:(nullable id<NativeThreadLauncher>)launcher;

- (void)doSomething;

@end
