// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from djinni_rest.djinni

#import <Foundation/Foundation.h>

typedef NS_ENUM(NSInteger, NativeHttpMethod)
{
    NativeHttpMethodGet,
    NativeHttpMethodPost,
    NativeHttpMethodPatch,
};
