// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from http.djinni

#import <Foundation/Foundation.h>


@protocol NativeHttpCallback

- (void)onSuccess:(int16_t)httpCode
             data:(nonnull NSString *)data;

- (void)onFailure;

@end
