// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from djinni_rest.djinni

#include "posts_index_response.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@protocol NativePostsIndexResponse;

namespace djinni_generated {

class PostsIndexResponse
{
public:
    using CppType = std::shared_ptr<::djinni_rest_gen::PostsIndexResponse>;
    using CppOptType = std::shared_ptr<::djinni_rest_gen::PostsIndexResponse>;
    using ObjcType = id<NativePostsIndexResponse>;

    using Boxed = PostsIndexResponse;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

