// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from api.djinni

#import "NativeHelloModel.h"
#include "hello_model.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class NativeHelloModel;

namespace djinni_generated {

struct HelloModel
{
    using CppType = ::djinni_rest_gen::HelloModel;
    using ObjcType = NativeHelloModel*;

    using Boxed = HelloModel;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
