// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from api.djinni

#import <Foundation/Foundation.h>

@interface NativePhotoModel : NSObject
- (nonnull instancetype)initWithId:(int64_t)id
                           albumId:(int64_t)albumId
                             title:(nonnull NSString *)title
                               url:(nonnull NSString *)url
                      thumbnailUrl:(nonnull NSString *)thumbnailUrl;
+ (nonnull instancetype)photoModelWithId:(int64_t)id
                                 albumId:(int64_t)albumId
                                   title:(nonnull NSString *)title
                                     url:(nonnull NSString *)url
                            thumbnailUrl:(nonnull NSString *)thumbnailUrl;

@property (nonatomic, readonly) int64_t id;

@property (nonatomic, readonly) int64_t albumId;

@property (nonatomic, readonly, nonnull) NSString * title;

@property (nonatomic, readonly, nonnull) NSString * url;

@property (nonatomic, readonly, nonnull) NSString * thumbnailUrl;

@end
