// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from api.djinni

#import "NativePhotoModel+Private.h"
#import "DJIMarshal+Private.h"
#include <cassert>

namespace djinni_generated {

auto PhotoModel::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::I64::toCpp(obj.id),
            ::djinni::I64::toCpp(obj.albumId),
            ::djinni::String::toCpp(obj.title),
            ::djinni::String::toCpp(obj.url),
            ::djinni::String::toCpp(obj.thumbnailUrl)};
}

auto PhotoModel::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[NativePhotoModel alloc] initWithId:(::djinni::I64::fromCpp(cpp.id))
                                        albumId:(::djinni::I64::fromCpp(cpp.album_id))
                                          title:(::djinni::String::fromCpp(cpp.title))
                                            url:(::djinni::String::fromCpp(cpp.url))
                                   thumbnailUrl:(::djinni::String::fromCpp(cpp.thumbnail_url))];
}

}  // namespace djinni_generated
