// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from djinni_rest.djinni

#import "NativePostModel.h"


@implementation NativePostModel

- (nonnull instancetype)initWithId:(int64_t)id
                             title:(nonnull NSString *)title
                              body:(nonnull NSString *)body
{
    if (self = [super init]) {
        _id = id;
        _title = [title copy];
        _body = [body copy];
    }
    return self;
}

+ (nonnull instancetype)postModelWithId:(int64_t)id
                                  title:(nonnull NSString *)title
                                   body:(nonnull NSString *)body
{
    return [[self alloc] initWithId:id
                              title:title
                               body:body];
}

- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p id:%@ title:%@ body:%@>", self.class, self, @(self.id), self.title, self.body];
}

@end
