// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from djinni_rest.djinni

#import "NativePostModel.h"
#import <Foundation/Foundation.h>


@protocol NativePostsIndexResponse

- (void)onSuccess:(nonnull NSArray<NativePostModel *> *)result;

- (void)onFailure;

@end
