// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from djinni_rest.djinni

#import <Foundation/Foundation.h>


@protocol NativeApiResponse

- (void)onSuccess:(nonnull NSString *)result;

- (void)onFailure;

@end
