// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from api.djinni

#import <Foundation/Foundation.h>

@interface NativeHelloModel : NSObject
- (nonnull instancetype)initWithWelcomeTitle:(nonnull NSString *)welcomeTitle;
+ (nonnull instancetype)helloModelWithWelcomeTitle:(nonnull NSString *)welcomeTitle;

@property (nonatomic, readonly, nonnull) NSString * welcomeTitle;

@end
