// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from api.djinni

#import "NativePostModel.h"
#import <Foundation/Foundation.h>


@protocol NativeApiPostsResponse

- (void)onIndexSuccess:(nonnull NSArray<NativePostModel *> *)result;

- (void)onShowSuccess:(nonnull NativePostModel *)result;

- (void)onFailure;

@end
