// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from djinni_rest.djinni

#include "api_posts_response.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@protocol NativeApiPostsResponse;

namespace djinni_generated {

class ApiPostsResponse
{
public:
    using CppType = std::shared_ptr<::djinni_rest_gen::ApiPostsResponse>;
    using CppOptType = std::shared_ptr<::djinni_rest_gen::ApiPostsResponse>;
    using ObjcType = id<NativeApiPostsResponse>;

    using Boxed = ApiPostsResponse;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

