// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from djinni_rest.djinni

#import <Foundation/Foundation.h>
@class NativeAsyncTask;


@protocol NativeThreadLauncher

- (void)startThread:(nonnull NSString *)name
              runFn:(nullable NativeAsyncTask *)runFn;

@end
