// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from api.djinni

#import "NativeApiPostsResponse+Private.h"
#import "NativeApiPostsResponse.h"
#import "DJIMarshal+Private.h"
#import "DJIObjcWrapperCache+Private.h"
#import "NativePostModel+Private.h"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

namespace djinni_generated {

class ApiPostsResponse::ObjcProxy final
: public ::djinni_rest_gen::ApiPostsResponse
, public ::djinni::ObjcProxyCache::Handle<ObjcType>
{
public:
    using Handle::Handle;
    void on_index_success(const std::vector<::djinni_rest_gen::PostModel> & c_result) override
    {
        @autoreleasepool {
            [Handle::get() onIndexSuccess:(::djinni::List<::djinni_generated::PostModel>::fromCpp(c_result))];
        }
    }
    void on_show_success(const ::djinni_rest_gen::PostModel & c_result) override
    {
        @autoreleasepool {
            [Handle::get() onShowSuccess:(::djinni_generated::PostModel::fromCpp(c_result))];
        }
    }
    void on_failure() override
    {
        @autoreleasepool {
            [Handle::get() onFailure];
        }
    }
};

}  // namespace djinni_generated

namespace djinni_generated {

auto ApiPostsResponse::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return ::djinni::get_objc_proxy<ObjcProxy>(objc);
}

auto ApiPostsResponse::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return dynamic_cast<ObjcProxy&>(*cpp).Handle::get();
}

}  // namespace djinni_generated
