// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from djinni_rest.djinni

#pragma once

#include <memory>

namespace djinni_rest_gen {

class ApiResponse;
class Http;
class PostsIndexResponse;
class ThreadLauncher;

class Api {
public:
    virtual ~Api() {}

    static std::shared_ptr<Api> create_api(const std::shared_ptr<ThreadLauncher> & launcher, const std::shared_ptr<Http> & http);

    virtual void do_something(const std::shared_ptr<ApiResponse> & api_response) = 0;

    virtual void get_posts_index(const std::shared_ptr<PostsIndexResponse> & posts_index_response) = 0;
};

}  // namespace djinni_rest_gen
