// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from api.djinni

#pragma once

#include <cstdint>
#include <memory>

namespace djinni_rest_gen {

class ApiPhotosResponse;
class ApiPostsResponse;
class Http;
class ThreadLauncher;
struct PostModel;

class Api {
public:
    virtual ~Api() {}

    static std::shared_ptr<Api> create_api(const std::shared_ptr<ThreadLauncher> & launcher, const std::shared_ptr<Http> & http);

    virtual void get_posts_index(const std::shared_ptr<ApiPostsResponse> & api_posts_response) = 0;

    virtual void get_posts_show(int64_t post_id, const std::shared_ptr<ApiPostsResponse> & api_posts_response) = 0;

    virtual bool is_post_valid(const PostModel & post_model) = 0;

    virtual void get_photos_index(const std::shared_ptr<ApiPhotosResponse> & api_photos_response) = 0;

    virtual void get_photos_show(int64_t photo_id, const std::shared_ptr<ApiPhotosResponse> & api_photos_response) = 0;
};

}  // namespace djinni_rest_gen
