// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from djinni_rest.djinni

#pragma once

#include <cstdint>
#include <memory>

namespace djinni_rest_gen {

class ApiPostsResponse;
class Http;
class ThreadLauncher;

class Api {
public:
    virtual ~Api() {}

    static std::shared_ptr<Api> create_api(const std::shared_ptr<ThreadLauncher> & launcher, const std::shared_ptr<Http> & http);

    static std::shared_ptr<Api> create();

    virtual void get_posts_index(const std::shared_ptr<ApiPostsResponse> & api_posts_response) = 0;

    virtual void get_posts_show(int64_t post_id, const std::shared_ptr<ApiPostsResponse> & api_posts_response) = 0;
};

}  // namespace djinni_rest_gen
