// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from api.djinni

#pragma once

#include <vector>

namespace djinni_rest_gen {

struct PhotoModel;

class ApiPhotosResponse {
public:
    virtual ~ApiPhotosResponse() {}

    virtual void on_index_success(const std::vector<PhotoModel> & result) = 0;

    virtual void on_show_success(const PhotoModel & result) = 0;

    virtual void on_failure() = 0;
};

}  // namespace djinni_rest_gen
