// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from api.djinni

#pragma once

#include <vector>

namespace djinni_rest_gen {

struct PostModel;

class ApiPostsResponse {
public:
    virtual ~ApiPostsResponse() {}

    virtual void on_index_success(const std::vector<PostModel> & result) = 0;

    virtual void on_show_success(const PostModel & result) = 0;

    virtual void on_failure() = 0;
};

}  // namespace djinni_rest_gen
