// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from djinni_rest.djinni

#pragma once

#include <string>

namespace djinni_rest_gen {

class ApiResponse {
public:
    virtual ~ApiResponse() {}

    virtual void on_success(const std::string & result) = 0;

    virtual void on_failure() = 0;
};

}  // namespace djinni_rest_gen
