// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from djinni_rest.djinni

#pragma once

namespace djinni_rest_gen {

class AsyncTask {
public:
    virtual ~AsyncTask() {}

    virtual void execute() = 0;
};

}  // namespace djinni_rest_gen
