// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from api.djinni

#pragma once

#include <string>
#include <utility>

namespace djinni_rest_gen {

struct HelloModel final {
    std::string welcome_title;

    HelloModel(std::string welcome_title_)
    : welcome_title(std::move(welcome_title_))
    {}
};

}  // namespace djinni_rest_gen
