// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from djinni_rest.djinni

#pragma once

#include <functional>

namespace djinni_rest_gen {

enum class HttpMethod : int {
    GET,
    POST,
    PATCH,
};

}  // namespace djinni_rest_gen

namespace std {

template <>
struct hash<::djinni_rest_gen::HttpMethod> {
    size_t operator()(::djinni_rest_gen::HttpMethod type) const {
        return std::hash<int>()(static_cast<int>(type));
    }
};

}  // namespace std
