// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from djinni_rest.djinni

#pragma once

#include <cstdint>
#include <string>

namespace djinni_rest_gen {

class HttpCallback {
public:
    virtual ~HttpCallback() {}

    virtual void on_success(int16_t http_code, const std::string & data) = 0;

    virtual void on_failure() = 0;
};

}  // namespace djinni_rest_gen
