// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from djinni_rest.djinni

#pragma once

#include <memory>
#include <string>

namespace djinni_rest_gen {

class HttpCallback;
enum class HttpMethod;

class Http {
public:
    virtual ~Http() {}

    virtual void send(HttpMethod http_method, const std::string & url, const std::shared_ptr<HttpCallback> & callback) = 0;
};

}  // namespace djinni_rest_gen
