// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from api.djinni

#pragma once

#include <cstdint>
#include <string>
#include <utility>

namespace djinni_rest_gen {

struct PhotoModel final {
    int64_t id;
    int64_t album_id;
    std::string title;
    std::string url;
    std::string thumbnail_url;

    PhotoModel(int64_t id_,
               int64_t album_id_,
               std::string title_,
               std::string url_,
               std::string thumbnail_url_)
    : id(std::move(id_))
    , album_id(std::move(album_id_))
    , title(std::move(title_))
    , url(std::move(url_))
    , thumbnail_url(std::move(thumbnail_url_))
    {}
};

}  // namespace djinni_rest_gen
