// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from djinni_rest.djinni

#pragma once

#include <vector>

namespace djinni_rest_gen {

struct PostModel;

class PostsIndexResponse {
public:
    virtual ~PostsIndexResponse() {}

    virtual void on_success(const std::vector<PostModel> & result) = 0;

    virtual void on_failure() = 0;
};

}  // namespace djinni_rest_gen
