// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from djinni_rest.djinni

#pragma once

#include <memory>
#include <vector>

namespace djinni_rest {

struct PostModel;

class PostsService {
public:
    virtual ~PostsService() {}

    static std::shared_ptr<PostsService> create();

    virtual std::vector<PostModel> get_posts_index() = 0;
};

}  // namespace djinni_rest
