// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from djinni_rest.djinni

#pragma once

#include <memory>
#include <string>

namespace djinni_rest_gen {

class AsyncTask;

class ThreadLauncher {
public:
    virtual ~ThreadLauncher() {}

    /** name is nullable */
    virtual void start_thread(const std::string & name, const std::shared_ptr<AsyncTask> & run_fn) = 0;
};

}  // namespace djinni_rest_gen
