// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from djinni_rest.djinni

package com.mycompany.djinni_rest;

import java.util.concurrent.atomic.AtomicBoolean;

public abstract class Api {
    public abstract void doSomething();

    public static native Api createApi(ThreadLauncher launcher);

    private static final class CppProxy extends Api
    {
        private final long nativeRef;
        private final AtomicBoolean destroyed = new AtomicBoolean(false);

        private CppProxy(long nativeRef)
        {
            if (nativeRef == 0) throw new RuntimeException("nativeRef is zero");
            this.nativeRef = nativeRef;
        }

        private native void nativeDestroy(long nativeRef);
        public void destroy()
        {
            boolean destroyed = this.destroyed.getAndSet(true);
            if (!destroyed) nativeDestroy(this.nativeRef);
        }
        protected void finalize() throws java.lang.Throwable
        {
            destroy();
            super.finalize();
        }

        @Override
        public void doSomething()
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            native_doSomething(this.nativeRef);
        }
        private native void native_doSomething(long _nativeRef);
    }
}
