// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from djinni_rest.djinni

package com.mycompany.djinni_rest;

public abstract class ApiResponse {
    public abstract void onSuccess(String result);

    public abstract void onFailure();
}
