// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from api.djinni

package com.mycompany.djinni_rest;

public final class HelloModel {


    /*package*/ final String mWelcomeTitle;

    public HelloModel(
            String welcomeTitle) {
        this.mWelcomeTitle = welcomeTitle;
    }

    public String getWelcomeTitle() {
        return mWelcomeTitle;
    }

    @Override
    public String toString() {
        return "HelloModel{" +
                "mWelcomeTitle=" + mWelcomeTitle +
        "}";
    }

}
