// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from djinni_rest.djinni

package com.mycompany.djinni_rest;

public abstract class Http {
    public abstract void send(HttpMethod httpMethod, String url, HttpCallback callback);
}
