// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from api.djinni

package com.mycompany.djinni_rest;

public final class PhotoModel {


    /*package*/ final long mId;

    /*package*/ final long mAlbumId;

    /*package*/ final String mTitle;

    /*package*/ final String mUrl;

    /*package*/ final String mThumbnailUrl;

    public PhotoModel(
            long id,
            long albumId,
            String title,
            String url,
            String thumbnailUrl) {
        this.mId = id;
        this.mAlbumId = albumId;
        this.mTitle = title;
        this.mUrl = url;
        this.mThumbnailUrl = thumbnailUrl;
    }

    public long getId() {
        return mId;
    }

    public long getAlbumId() {
        return mAlbumId;
    }

    public String getTitle() {
        return mTitle;
    }

    public String getUrl() {
        return mUrl;
    }

    public String getThumbnailUrl() {
        return mThumbnailUrl;
    }

    @Override
    public String toString() {
        return "PhotoModel{" +
                "mId=" + mId +
                "," + "mAlbumId=" + mAlbumId +
                "," + "mTitle=" + mTitle +
                "," + "mUrl=" + mUrl +
                "," + "mThumbnailUrl=" + mThumbnailUrl +
        "}";
    }

}
