// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from djinni_rest.djinni

package com.mycompany.djinni_rest;

import java.util.ArrayList;
import java.util.concurrent.atomic.AtomicBoolean;

public abstract class PostsService {
    public abstract ArrayList<PostModel> getPostsIndex();

    public static native PostsService create();

    private static final class CppProxy extends PostsService
    {
        private final long nativeRef;
        private final AtomicBoolean destroyed = new AtomicBoolean(false);

        private CppProxy(long nativeRef)
        {
            if (nativeRef == 0) throw new RuntimeException("nativeRef is zero");
            this.nativeRef = nativeRef;
        }

        private native void nativeDestroy(long nativeRef);
        public void destroy()
        {
            boolean destroyed = this.destroyed.getAndSet(true);
            if (!destroyed) nativeDestroy(this.nativeRef);
        }
        protected void finalize() throws java.lang.Throwable
        {
            destroy();
            super.finalize();
        }

        @Override
        public ArrayList<PostModel> getPostsIndex()
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_getPostsIndex(this.nativeRef);
        }
        private native ArrayList<PostModel> native_getPostsIndex(long _nativeRef);
    }
}
