// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from djinni_rest.djinni

package com.mycompany.djinni_rest;

public final class PostModel {


    /*package*/ final long mId;

    /*package*/ final String mTitle;

    /*package*/ final String mBody;

    public PostModel(
            long id,
            String title,
            String body) {
        this.mId = id;
        this.mTitle = title;
        this.mBody = body;
    }

    public long getId() {
        return mId;
    }

    public String getTitle() {
        return mTitle;
    }

    public String getBody() {
        return mBody;
    }

    @Override
    public String toString() {
        return "PostModel{" +
                "mId=" + mId +
                "," + "mTitle=" + mTitle +
                "," + "mBody=" + mBody +
        "}";
    }

}
