// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from djinni_rest.djinni

package com.mycompany.djinni_rest;

import java.util.ArrayList;

public abstract class PostsIndexResponse {
    public abstract void onSuccess(ArrayList<PostModel> result);

    public abstract void onFailure();
}
