// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from djinni_rest.djinni

package com.mycompany.djinni_rest;

public abstract class ThreadLauncher {
    public abstract void startThread(String name, AsyncTask runFn);
}
